version: '3.8'
services:
  dev-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bookmanagement
    networks:
      - localhost
  test-db:
    image: postgres:latest
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bookmanagement
    networks:
      - localhost

networks:
  localhost:
